### ISSUE TITLE
Version 2.1

### ISSUE THREAD

**Issue by F0rsaken** [owlsdepartment/ovee#15]
New features:

 - [x] New Reactivity system from Vue 3 witj new decorators: `@computed` and `@watchEffect` #11 

Fixes:

- [x] Catching errors in lifecycle hooks #3 
- [x] Fix decorators inheritance #2 

Refactors:

- [x] Update ESLint and Prettier #13 
- [x] New Logging system #12 
- [x] CHANGELOG for tracking changes #14
